# Generated by Django 3.1 on 2020-09-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pavada',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
